name: CI/CD PyTestPlugin

on:
  push:
  workflow_dispatch:

jobs:
  compile:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup the Java JDK 17 and cache gradle dependencies
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'gradle'
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Run assemble gradle task
          run: ./gradlew assemble

  jvm-version:
    runs-on: ubuntu-latest
    needs:
      - compile
    outputs:
      versions: ${{ steps.versions.outputs.list }}
    steps:
      - run: |
          ruby -e 'puts "list=#{((16..19).to_a + [8, 11]).to_s}"' >> $GITHUB_OUTPUT
        id: versions

  test:
    needs:
      - jvm-version
    strategy:
      matrix:
        java: ${{ fromJson(needs.jvm-version.outputs.versions) }}
        os: [ windows, macos, ubuntu ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Setup the Java JDK 17 and cache gradle dependencies ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test --stacktrace --warning-mode all

  success:
    runs-on: ubuntu-latest
    needs:
      - compile
      - test
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}